{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Playlist tracks\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.1229.0 (24.05)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "de-DE",
    "tables": [
      {
        "name": "Playlist tracks",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48e52b4c-1b66-44f2-b67f-38b303fc4489",
            "sourceColumn": "title",
            "summarizeBy": "none"
          },
          {
            "name": "album",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d95cfb60-7293-4a3b-a4d4-8175511265dc",
            "sourceColumn": "album",
            "summarizeBy": "none"
          },
          {
            "name": "duration_seconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46acfb0a-3d95-4cdd-ab79-7a5bb93f0f77",
            "sourceColumn": "duration_seconds",
            "summarizeBy": "none"
          },
          {
            "name": "cover",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "4142cc25-ddda-4b2e-b1a6-777222bbcb96",
            "sourceColumn": "cover",
            "summarizeBy": "none"
          },
          {
            "name": "artist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5bd1b0e-91c1-497b-95c8-32156e537afc",
            "sourceColumn": "artist",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fd7600cf-332b-4b7d-9c78-79b98959fcb1",
        "measures": [
          {
            "name": "Total duration",
            "expression": [
              "",
              "VAR _zeit=SUM('Playlist tracks'[duration_seconds])",
              "VAR _sekunden=MOD(_zeit,60)",
              "VAR _minuten=MOD(INT(_zeit/60),60)",
              "VAR _stunden=INT(_zeit/3600)",
              "RETURN",
              "_stunden & \":\" & RIGHT(\"0\"&_minuten,2) & \":\" & RIGHT(\"0\"&_sekunden,2)"
            ],
            "lineageTag": "fffdb134-3ce7-4967-a903-6fdc5dbc7bd5"
          },
          {
            "name": "# of distinct songs",
            "expression": "DISTINCTCOUNT('Playlist tracks'[title])",
            "formatString": "0",
            "lineageTag": "b336fe77-441c-4fdb-ac57-bf874369ac33"
          },
          {
            "name": "Duration in seconds",
            "expression": [
              "SUM('Playlist tracks'[duration_seconds])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b2ae79c8-37a9-40a3-8543-025235b8487f"
          },
          {
            "name": "Total # of songs",
            "expression": "COUNTROWS('Playlist tracks')",
            "formatString": "0",
            "lineageTag": "27082a7f-9503-4ea4-88d8-92c28886ed79"
          },
          {
            "name": "Average duration",
            "expression": [
              "",
              "VAR _zeit=AVERAGE('Playlist tracks'[duration_seconds])",
              "VAR _sekunden=INT(MOD(_zeit,60))",
              "VAR _minuten=MOD(INT(_zeit/60),60)",
              "RETURN",
              "RIGHT(\"0\"&_minuten,2) & \":\" & RIGHT(\"00\"&_sekunden,2)"
            ],
            "lineageTag": "cb34b741-bb90-4fb1-8859-3f457e1938d3"
          },
          {
            "name": "Duration in minutes",
            "expression": "SUM('Playlist tracks'[duration_seconds])/60",
            "formatString": "0.00",
            "lineageTag": "1db3fa0b-8b9a-4b10-9d43-91697ec8647e"
          }
        ],
        "partitions": [
          {
            "name": "Playlist tracks",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Json.Document(File.Contents(\"C:\\Users\\renee\\OneDrive\\Dokumente\\IT Projekte\\Metallische Liste\\sample.json\")),",
                "    #\"Converted to Table\" = Table.FromRecords({Source}),",
                "    #\"Expanded author\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"author\", {\"name\", \"id\"}, {\"author.name\", \"author.id\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded author\",{{\"id\", type text}, {\"owned\", type logical}, {\"privacy\", type text}, {\"title\", type text}, {\"thumbnails\", type any}, {\"description\", type text}, {\"author.name\", type text}, {\"author.id\", type any}, {\"views\", Int64.Type}, {\"duration\", type text}, {\"trackCount\", Int64.Type}, {\"related\", type any}, {\"tracks\", type any}, {\"duration_seconds\", Int64.Type}}),",
                "    #\"Expanded tracks\" = Table.ExpandListColumn(#\"Changed Type\", \"tracks\"),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Expanded tracks\",{\"tracks\"}),",
                "    #\"Expanded Records\" = Table.ExpandRecordColumn(#\"Removed Other Columns\",\"tracks\",{\"videoId\",\"title\",\"thumbnails\",\"artists\",\"views\",\"duration_seconds\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Records\",{{\"views\", \"album\"}}),",
                "    #\"Expanded artists\" = Table.ExpandListColumn(#\"Renamed Columns\", \"artists\"),",
                "    #\"Expanded artist record\" = Table.ExpandRecordColumn(#\"Expanded artists\",\"artists\",{\"name\"}),",
                "    #\"Expanded thumbnails\" = Table.ExpandListColumn(#\"Expanded artist record\", \"thumbnails\"),",
                "    #\"Expanded thumbnails record\" = Table.ExpandRecordColumn(#\"Expanded thumbnails\",\"thumbnails\",{\"url\"}),",
                "    #\"Inserted Text Between Delimiters\" = Table.AddColumn(#\"Expanded thumbnails record\", \"Text Between Delimiters\", each Text.BetweenDelimiters([url], \"=w\", \"-\"), type text),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Inserted Text Between Delimiters\", each ([Text Between Delimiters] <> \"60\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Text Between Delimiters\", \"videoId\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns\",{{\"name\", \"artist\"}}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Renamed Columns1\", {\"title\", \"url\", \"album\", \"duration_seconds\"}, {{\"artists\", each Text.Combine([artist],\", \"), type text}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Grouped Rows\",{{\"artists\", \"artist\"}, {\"url\", \"cover\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_7633ef39-a902-4497-8bad-a8a66e3ffd9e",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7d3081ab-2ace-485a-ac36-0e08f20a800c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "565f84cd-24a6-44cb-9afa-2549dda547fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eb2f7d76-68eb-4a15-97be-2901b1f9f853",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "eebd5e8b-4eff-46f5-93fe-ec579f03eb40",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2f220fe9-92ac-4662-b361-8fae40b3dd3e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e6bba610-f5a9-4d40-9c76-b93cc52f7fb3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "60ecb84b-3ac5-4812-9cca-2160a678bcd8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "df7c3ed9-7b85-4e9d-8d62-fea7c0b4183b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "478e3e0d-485c-4f22-81bd-2800a2265a68",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7e6fef92-7546-4f86-86ca-02cfecfff2b0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9469eb1f-381a-4738-b13a-19a0c180cf95",
                "ordinal": 3
              }
            ],
            "lineageTag": "3e6cba52-35ee-4d20-b26c-579fe1fcc0db"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9db6aae2-0285-42fb-a94c-97ed0dec42df",
        "partitions": [
          {
            "name": "DateTableTemplate_7633ef39-a902-4497-8bad-a8a66e3ffd9e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}